# config server port
server:
  port: 8888

# config file configuration location based on git repository uri
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ciazhar/clorus-config

# config username and password to access git repository
#          username:
#          password:

# config json pretty print
  jackson:
    serialization:
      indent_output: true


